import cv2
import os
import time

#generated by chat gpt free may24th, 2023 version
#uses camera to capture an image every 15 secs,
#i used it for collecting images for custom data sets
# Define the interval in seconds for capturing images
capture_interval = 15

# Define the output folder to save the images
output_folder = "image_folder"

# Create the output folder if it doesn't exist
os.makedirs(output_folder, exist_ok=True)


def capture_and_save_image():
    # Open the camera
    cap = cv2.VideoCapture(0)

    # Check if the camera is opened successfully
    if not cap.isOpened():
        print("Failed to open the camera")
        return

    while True:
        # Read a frame from the camera
        ret, frame = cap.read()
        if not ret:
            print("Failed to capture frame from the camera")
            break

        # Generate a unique filename for the image based on the current timestamp
        timestamp = int(time.time())
        filename = f"{output_folder}/image_{timestamp}.jpg"

        # Save the image to the output folder
        cv2.imwrite(filename, frame)
        print(f"Image saved: {filename}")

        # Wait for the specified interval before capturing the next image
        time.sleep(capture_interval)

    # Release the camera and close any open windows
    cap.release()
    cv2.destroyAllWindows()


# Start capturing and saving images
capture_and_save_image()
