#!/usr/bin/env python3
# coding=utf-8
import time
from Arm_Lib import Arm_Device
import cv2

#manually control the yahboom 6dof bot using sliders
#generated by chat gpt may 24th free version

def nothing(x):
    pass

Arm = Arm_Device()
time.sleep(.1)

# Create a window for the trackbars and camera output
cv2.namedWindow("Control")

# Create trackbars
cv2.createTrackbar("angle1", "Control", 0, 180, nothing)
cv2.createTrackbar("angle2", "Control", 0, 180, nothing)
cv2.createTrackbar("angle3", "Control", 0, 180, nothing)
cv2.createTrackbar("angle4", "Control", 0, 180, nothing)
cv2.createTrackbar("angle5", "Control", 0, 180, nothing)
cv2.createTrackbar("angle6", "Control", 0, 180, nothing)

cv2.setTrackbarPos("angle1", "Control", 90)
cv2.setTrackbarPos("angle2", "Control", 90)
cv2.setTrackbarPos("angle3", "Control", 90)
cv2.setTrackbarPos("angle4", "Control", 90)
cv2.setTrackbarPos("angle5", "Control", 90)
cv2.setTrackbarPos("angle6", "Control", 90)

def main():
    cap = cv2.VideoCapture(0)
    if not cap.isOpened():
        print("Failed to open the video capture")
        return

    while True:
        ret, frame = cap.read()
        if not ret:
            break

        cv2.imshow("Control", frame)

        angle1 = cv2.getTrackbarPos("angle1", "Control")
        angle2 = cv2.getTrackbarPos("angle2", "Control")
        angle3 = cv2.getTrackbarPos("angle3", "Control")
        angle4 = cv2.getTrackbarPos("angle4", "Control")
        angle5 = cv2.getTrackbarPos("angle5", "Control")
        angle6 = cv2.getTrackbarPos("angle6", "Control")

        Arm.Arm_serial_servo_write(1, angle1, 10)
        Arm.Arm_serial_servo_write(2, angle2, 10)
        Arm.Arm_serial_servo_write(3, angle3, 10)
        Arm.Arm_serial_servo_write(4, angle4, 10)
        Arm.Arm_serial_servo_write(5, angle5, 10)
        Arm.Arm_serial_servo_write(6, angle6, 10)

        if cv2.waitKey(1) == 27:  # Press 'Esc' to exit
            break

    cap.release()
    cv2.destroyAllWindows()

try:
    main()
except KeyboardInterrupt:
    print("Program closed!")
    pass

del Arm
