import time
from adafruit_servokit import ServoKit

#this script was generated by chat gpt3.5 august 3rd, 2023 version

class ServoController:
    def __init__(self, servo_channel=0, min_angle=30, max_angle=110, servo_speed=2, direction=1):
        self.kit = ServoKit(channels=16)  # Change the number of channels as needed
        self.servo_channel = servo_channel
        self.min_angle = min_angle
        self.max_angle = max_angle
        self.servo_speed = servo_speed
        self.direction = direction

    def move_servo(self):
        try:
            while True:
                # Move the servo from min to max angle
                for angle in range(self.min_angle, self.max_angle + 1, self.servo_speed * self.direction):
                    self.kit.servo[self.servo_channel].angle = angle
                    time.sleep(0.01)  # Adjust delay for smoother motion

                # Move the servo from max to min angle
                for angle in range(self.max_angle, self.min_angle - 1, -self.servo_speed * self.direction):
                    self.kit.servo[self.servo_channel].angle = angle
                    time.sleep(0.01)  # Adjust delay for smoother motion

        except KeyboardInterrupt:
            # Stop the servo and exit gracefully when Ctrl+C is pressed
            self.kit.servo[self.servo_channel].angle = None

if __name__ == "__main__":
    servo_controller = ServoController(servo_channel=0, min_angle=30, max_angle=110, servo_speed=2, direction=1)
    servo_controller.move_servo()
